# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Create app directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .


EXPOSE 3000


CMD ["npm", "start"]
